solution
mate-academy/layout_catalog_hovers pull request #11
Opened 2021-08-23 13:59 UTC by sgw8

- [DEMO LINK](https://sgw8.github.io/layout_catalog_hovers/)

2021-08-23 14:02 UTC, CouldSweeT approved these changes

2021-08-25 14:19 UTC, OleksiiBlezniuk requested changes
Когда пропадает hover с карточки - резко меняется размер, сделай чтобы это было плавно, как и при hover🙂

2021-08-25 15:01 UTC, OleksiiBlezniuk requested changes

2021-08-25 15:14 UTC, OleksiiBlezniuk requested changes

2021-08-25 15:14 UTC, OleksiiBlezniuk commented on src/styles/_catalog.scss
> +    transition-duration: $card-duration;
Используй правило "transition" и укажи в нём какое свойство ты анимируешь и длительность анимации

2021-08-26 07:32 UTC, OleksiiBlezniuk approved these changes

2021-08-31 09:31 UTC, OleksiiBlezniuk approved these changes

2024-05-06 12:54 UTC, closed without merging