added scale for cards + hover for text. added hover for header
mate-academy/layout_catalog_hovers pull request #1160
Opened 2022-11-06 13:15 UTC by fallowlone

- [DEMO LINK](https://official-artem.github.io/layout_catalog_hovers/)

2022-11-08 15:10 UTC, GabrielMaksimovich requested changes
Good job, I don't know what to add more

2022-11-08 15:10 UTC, GabrielMaksimovich commented on src/styles/blocks/header.scss
> +
maybe put nav to own file, cause its a block

2022-11-09 13:01 UTC, solaryasha requested changes

2022-11-09 13:17 UTC, solaryasha approved these changes
👍

2022-11-09 13:17 UTC, solaryasha commented on src/styles/blocks/catalog.scss
> +    transition: transform $transition-duration linear,
linear - it's the default value, you don't need to mention it :)

2026-03-01 22:59 UTC, closed without merging