Catalog hovers
mate-academy/layout_catalog_hovers pull request #1293
Opened 2022-11-29 10:09 UTC by mdm-21

- [DEMO LINK](https://mdm-21.github.io/layout_catalog_hovers/)

2022-11-29 17:51 UTC, SanyaBratashchuk requested changes

2022-11-29 17:51 UTC, SanyaBratashchuk commented on src/styles/blocks/catalog.scss
> +    transition: 300ms;
```suggestion
    transition: transform 300ms, color 300ms;
```
And move 300ms to the variable

2022-11-29 17:51 UTC, SanyaBratashchuk commented on src/styles/blocks/header.scss
> +    }
```suggestion
    font-weight: 500;
     transition: color 300ms;

    &:hover {
      color: #00acdc;
    }
```

2022-11-30 18:28 UTC, Viktor-Kost approved these changes

2023-11-30 10:33 UTC, closed without merging