update: add transition on hover effect
mate-academy/layout_catalog_hovers pull request #1390
Opened 2022-12-15 21:15 UTC by Borys-Andrew

- [DEMO LINK](https://borys-andrew.github.io/layout_catalog_hovers/)

2022-12-18 02:58 UTC, Kardash-Oleksandr approved these changes

2022-12-18 02:58 UTC, Kardash-Oleksandr commented on src/styles/blocks/catalog.scss
> +    transition: transform 300ms color 300ms;
move duration to variable

2022-12-18 02:58 UTC, Kardash-Oleksandr commented on src/styles/blocks/header.scss
> +    transition: color 300ms;
move duration to variable

2022-12-19 10:24 UTC, ArturErmolenko requested changes
transition doesn't work

https://user-images.githubusercontent.com/94292654/208404124-516c4ba2-1993-411b-9679-abbe39b38a2d.mov

2022-12-20 14:34 UTC, ArturErmolenko approved these changes

2022-12-20 14:34 UTC, ArturErmolenko commented on src/styles/blocks/catalog.scss
> +    transition: transform $duration;
```suggestion
    transition: transform $duration, color $duration;
```
you forget `,` that's why transition didn't work last time

2025-05-01 20:15 UTC, closed without merging