links and cards transforming now
mate-academy/layout_catalog_hovers pull request #1445
Opened 2023-01-09 17:55 UTC by DanielLinker17

- [DEMO LINK](https://DanielLinker17.github.io/layout_catalog_hovers/)

2023-01-10 18:41 UTC, SanyaBratashchuk requested changes

2023-01-10 18:41 UTC, SanyaBratashchuk commented on src/styles/blocks/catalog.scss
> +      transition: $change-speed $smooth-timing-function;
Fix it everywhere

2023-01-10 18:41 UTC, SanyaBratashchuk commented on src/styles/utils/variables.scss
> +$navy-blue: #34568b;
```suggestion
$navy-blue: #34568b;

```

2023-01-11 19:07 UTC, SanyaBratashchuk requested changes

2023-01-11 19:07 UTC, SanyaBratashchuk commented on src/styles/blocks/header.scss
> +    transition: $change-speed $smooth-timing-function;
specify properties for which you apply transition

2023-01-11 19:07 UTC, SanyaBratashchuk commented on src/styles/blocks/catalog.scss
> +    transition: $change-speed $smooth-timing-function;
specify properties for which you apply transition

2023-01-11 19:07 UTC, SanyaBratashchuk commented on src/styles/utils/variables.scss
> +$navy-blue: #34568b;
Add empty line in the end of file

2023-01-13 16:23 UTC, DarkMistyRoom approved these changes

2025-07-29 00:25 UTC, closed without merging