done
mate-academy/layout_catalog_hovers pull request #1470
Opened 2023-01-16 19:18 UTC by maxonshev

https://maxonshev.github.io/layout_catalog_hovers/

2023-01-17 19:25 UTC, marina-tilniak requested changes

2023-01-17 19:25 UTC, marina-tilniak commented on src/styles/blocks/catalog.scss
> +    transition: transform 0.3s, color 0.3s;
move 0.3s to variable

2023-01-17 21:18 UTC, marina-tilniak commented on src/styles/blocks/header.scss
> +    transition: color 0.3s;
why you didn't use your variable here?

2023-01-18 08:28 UTC, tetiana-ivanchenko approved these changes

2025-03-07 10:52 UTC, closed without merging