Solution
mate-academy/layout_catalog_hovers pull request #1492
Opened 2023-01-24 07:33 UTC by Zelinskyi-Serhii

- [DEMO LINK](https://Zelinskyi-Serhii.github.io/layout_catalog_hovers/)

2023-02-01 16:29 UTC, kirill-vypirovskyi approved these changes
Looks good for me

2023-02-02 11:05 UTC, illiarerun requested changes

2023-02-02 11:05 UTC, illiarerun commented on src/styles/blocks/catalog.scss
> +    transition: $transition-time;
you should ALWAYS specify every property in transition

2023-02-02 11:05 UTC, illiarerun commented on src/styles/blocks/navigation.scss
> +    transition: $transition-time;
same even here

2023-02-02 19:55 UTC, illiarerun requested changes

2023-02-02 19:55 UTC, illiarerun commented on src/styles/blocks/catalog.scss
> +    transition: all $transition-time;
don't use all in your transitions, better specify all properties to make them refactorable in future

2023-02-03 07:44 UTC, illiarerun approved these changes

2023-07-12 20:27 UTC, closed without merging