catalog_hovers
mate-academy/layout_catalog_hovers pull request #1578
Opened 2023-02-06 19:07 UTC by SergeyShapovalenko

- [DEMO LINK](https://SergeyShapovalenko.github.io/layout_catalog_hovers/)

2023-02-06 19:29 UTC, loralevitska requested changes
Almost perfect! Let's improve

2023-02-06 19:29 UTC, loralevitska commented on src/styles/blocks/header.scss
> +    transition-duration: $transmission-duration;
Add property to  transition ![image](https://user-images.githubusercontent.com/70009205/217066376-d17c185b-28c1-4ee1-a04b-13a382b3ab15.png)
Fix everywhere

2023-02-07 16:19 UTC, slavanosatskyi commented on src/styles/variables/variables.scss
> +$transition: transform 300ms, color 300ms;
minor in real life such variables are rear cases. in your case it was better to move 300ms to variable only. As nav links do not change their transform property on hover event.

2023-02-07 16:20 UTC, slavanosatskyi approved these changes
Nice work!

2023-11-15 11:47 UTC, closed without merging