Completed the catalog hovers task
mate-academy/layout_catalog_hovers pull request #1869
Opened 2023-04-25 19:13 UTC by Shevtsooov

- [DEMO LINK](https://Shevtsooov.github.io/layout_catalog_hovers/)

2023-04-26 11:32 UTC, serentinos requested changes
Good job! Here are a few suggestions

2023-04-26 11:32 UTC, serentinos commented on src/styles/blocks/catalog.scss
> +  }
You can nest hover inside card style. 
```
&__card {
  &:hover {
    transform: scale(120%);
    color: #34568b;
  }
}
```
Also better use the coefficient for scale(), not presents I guess.

[checklist p3](https://github.com/mate-academy/layout_catalog_hovers/blob/master/checklist.md)

2023-04-26 11:32 UTC, serentinos commented on src/styles/blocks/header.scss
> +  }
Also in this situation
[checklist p3](https://github.com/mate-academy/layout_catalog_hovers/blob/master/checklist.md)

2023-04-26 18:30 UTC, Shevtsooov commented
@serentinos Thank you! Corected the nesting.

2023-04-27 06:36 UTC, andrusb21 approved these changes
Good Job! 🔥🔥🔥

2023-04-29 23:57 UTC, silchyn approved these changes

2023-04-29 23:57 UTC, silchyn commented on src/styles/blocks/catalog.scss
> +    transition: 300ms;
so why you don't use your variable here?

2023-04-29 23:57 UTC, silchyn commented on src/styles/blocks/catalog.scss
> +    transition: 300ms;
only add transition for needed properties

2024-05-05 10:55 UTC, closed without merging