Catalog hover created
mate-academy/layout_catalog_hovers pull request #218
Opened 2021-11-29 10:00 UTC by gnosis-frog

- [DEMO LINK](https://gnosis-frog.github.io/layout_catalog_hovers/)

2021-11-30 10:37 UTC, Rom911 requested changes

2021-11-30 10:37 UTC, Rom911 commented on src/styles/_catalog.scss
> +      color 300ms;
пропиши в строку 
`transition: transform 300ms, color 300ms;`

или оба значения перенеси
```
transition: 
      transform 300ms,
      color 300ms;
```

2021-11-30 21:21 UTC, Rom911 approved these changes
ok

2021-12-01 07:37 UTC, danheim approved these changes

2023-02-08 11:03 UTC, closed without merging