hover catalog
mate-academy/layout_catalog_hovers pull request #23
Opened 2021-08-25 18:51 UTC by caelum29

- [DEMO LINK](https://caelum29.github.io/layout_catalog_hovers/)

2021-08-26 13:32 UTC, oksana-onopa approved these changes
Все супер! 👍

2021-08-27 07:37 UTC, OleksiiBlezniuk requested changes
Давай ещё добавим hover-эффект на ссылку🙂

<img width="547" alt="Снимок экрана 2021-08-27 в 10 37 13" src="https://user-images.githubusercontent.com/84275496/131090828-085ba844-0713-481f-b476-d108551a3e3e.png">

2021-08-27 09:18 UTC, OleksiiBlezniuk approved these changes
Не забывай заново деплоить проект, когда вносишь в него изменения

2021-08-31 09:37 UTC, OleksiiBlezniuk approved these changes

2025-10-31 11:25 UTC, closed without merging