initial commit
mate-academy/layout_catalog_hovers pull request #311
Opened 2022-01-27 15:02 UTC by vsevolodk-qa

[DEMO LINK](https://moodealer.github.io/layout_catalog_hovers/)

2022-01-27 15:41 UTC, addKiwi requested changes
Майже готово лише потрібно змінити швидкість

2022-01-27 15:41 UTC, addKiwi commented on src/styles/_catalog.scss
> +    transition: transform 0.3ms ease-in-out, color 0.3ms ease-in-out;
Зміни швидкість 300ms або 0,3s

2022-01-27 15:41 UTC, addKiwi commented on src/styles/_header.scss
> +    transition: color 0.3ms ease-in-out;
Швидкість у readme 300ms

2022-01-27 18:21 UTC, addKiwi approved these changes
Good job!

2022-01-28 10:11 UTC, Ihor-Karpyn approved these changes

2022-04-28 10:07 UTC, closed without merging