yuliia-nudyk_catalog-hovers
mate-academy/layout_catalog_hovers pull request #334
Opened 2022-02-20 20:00 UTC by yuliia-nudyk

- DEMO LINK - https://yuliia-nudyk.github.io/layout_catalog_hovers/

2022-02-21 11:37 UTC, ArtemTopolskyi requested changes

2022-02-21 11:37 UTC, ArtemTopolskyi commented on src/styles/_catalog.scss
> +    transition: 300ms;
don't use transition: all, write only neede properties
```suggestion
    transition: transform 300ms, color 300ms;
```

2022-02-21 11:37 UTC, ArtemTopolskyi commented on src/styles/_header.scss
> +    transition: 300ms;
don't use transition: all, write only neede properties
```suggestion
    transition: color 300ms;
```

2022-02-22 09:54 UTC, vitaliy-martynyuk requested changes
fix the responsive( [here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) is a full guide about `flex` for your convenience )
<img width="874" alt="Screen Shot 2022-02-22 at 11 51 23 AM" src="https://user-images.githubusercontent.com/84335906/155107321-99c5f64d-6fb9-4845-b2e8-719af2133355.png">

2022-05-24 13:58 UTC, closed without merging