solution
mate-academy/layout_catalog_hovers pull request #427
Opened 2022-04-03 22:32 UTC by yelnikov-andrii

- [DEMO LINK](https://yelnikov-andrii.github.io/layout_catalog_hovers/)

2022-04-07 17:07 UTC, AnastasiyaSopotnytska commented on src/styles/_catalog.scss
> +      animation-duration: 300ms;
Move this to element. 
Animation will not be smooth when mouse leave element.

2022-04-08 09:04 UTC, Anna-Tkachenko requested changes

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_catalog.scss
> +    transition-duration: 300ms;
You should specify properties that can be changeable

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_catalog.scss
> +    transition-duration: 300ms;
Don't use 'all' as transition-property

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_catalog.scss
> +      color: #34568b;
Create variables for colors

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_catalog.scss
> +      transition-duration: 300ms;
It's redundant here

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_catalog.scss
> +    &:hover {
Styles for nav should be in nav.scss file

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_header.scss
> +    transition-duration: 300ms;
You should specify properties that can be changeable

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_header.scss
> +      }
it's redundant here, you should only change text color for nav__link, check the task

2022-04-08 09:04 UTC, Anna-Tkachenko commented on src/styles/_header.scss
>    }
It's redundant, use only correct transition for your card and change transform property on hover state

2022-04-11 15:51 UTC, Denchepornyuk requested changes
<img width="541" alt="Screenshot 2022-04-11 at 18 50 45" src="https://user-images.githubusercontent.com/37452763/162780386-4b1a36e4-fd82-411e-bb54-ce128175a7f8.png">
fix all comments from Anna

2022-04-12 09:53 UTC, denys-cheporniuk approved these changes

2024-03-19 14:41 UTC, closed without merging