animation added
mate-academy/layout_catalog_hovers pull request #428
Opened 2022-04-05 06:22 UTC by ZUBOV-ILLIA

- [DEMO LINK](https://ZUBOV-ILLIA.github.io/layout_catalog_hovers/)

2022-04-06 12:47 UTC, EnjSadman approved these changes

2022-04-06 12:58 UTC, Anna-Tkachenko requested changes

2022-04-06 12:58 UTC, Anna-Tkachenko commented on src/styles/_catalog.scss
> +    transition: 300ms;
You should specify changeable properties
Don't set transition for all properties

2022-04-07 11:22 UTC, Anna-Tkachenko approved these changes
Good job! 👍

2025-03-07 09:13 UTC, closed without merging