added amazing transition
mate-academy/layout_catalog_hovers pull request #479
Opened 2022-05-11 13:21 UTC by vsupruniuk

- [DEMO LINK](https://vsupruniuk.github.io/layout_catalog_hovers/)

2022-05-13 09:28 UTC, stanislav-topikha approved these changes

2022-05-16 13:05 UTC, Olexandr6 requested changes
Almost done👍

2022-05-16 13:05 UTC, Olexandr6 commented on src/styles/_catalog.scss
> +    transition: all 300ms;
You don't need `transition` for all animations, only for transform and color

2022-05-16 13:05 UTC, Olexandr6 commented on src/styles/_header.scss
> +    transition: 300ms;
[Checklist](https://github.com/mate-academy/layout_catalog_hovers/blob/master/checklist.md) 10th item

2022-05-17 17:20 UTC, Olexandr6 approved these changes

2024-01-12 12:34 UTC, closed without merging