first commit
mate-academy/layout_catalog_hovers pull request #573
Opened 2022-06-06 13:34 UTC by pavel-gutsal

https://pavel-gutsal.github.io/layout_catalog_hovers/

2022-06-07 17:47 UTC, ArturErmolenko requested changes

2022-06-07 17:47 UTC, ArturErmolenko commented on src/styles/_catalog.scss
> +    transition: all 0.3s ease-in-out;
Лучше явно указывать свойство которое анимируеш
```suggestion
    transition: transform 0.3s ease-in-out;
```

2022-06-07 17:47 UTC, ArturErmolenko commented on src/styles/_header.scss
> +    transition: all 0.3s ease-in-out;
same

2022-06-13 09:42 UTC, pavel-gutsal commented
transition values were changed to specific changes.

2022-06-14 10:58 UTC, ArtemTopolskyi requested changes

2022-06-14 14:26 UTC, pavel-gutsal commented
transition-property: transform , color;             was added to class

2022-06-16 13:01 UTC, Bohdan-Maksymiuk approved these changes

2022-06-16 13:01 UTC, Bohdan-Maksymiuk commented on src/styles/_catalog.scss
> +    transition-property: transform , color ;
```suggestion
    transition-property: transform, color;
```

2022-10-07 11:14 UTC, closed without merging