commit
mate-academy/layout_catalog_hovers pull request #605
Opened 2022-06-13 11:31 UTC by Kras4iy

- [DEMO LINK](https://Kras4iy.github.io/layout_catalog_hovers/)

2022-06-13 17:54 UTC, TwoAndMore reviewed
Good Job 🔥

2022-06-13 17:54 UTC, TwoAndMore commented on src/styles/_catalog.scss
> +    transition: all 0.3s linear;
transition all краще не писати

2022-06-14 08:54 UTC, ivan-kadykalo commented on src/styles/_catalog.scss
> +    transition: all 0.3s linear;
all is a default parameter, there is no need to write it.
Anyway, you should write the parameters which should apply to this transition
For example: `transition: color 0.3s`

2022-06-14 08:55 UTC, ivan-kadykalo requested changes
Almost everything is fine. Only one fix left💪

2022-06-14 09:07 UTC, ivan-kadykalo approved these changes
🔥

2026-04-07 16:39 UTC, closed without merging