added transitions
mate-academy/layout_catalog_hovers pull request #852
Opened 2022-08-21 16:12 UTC by ihorandrianov

- [DEMO LINK](https://ihorandrianov.github.io/layout_catalog_hovers/)

2022-08-30 07:20 UTC, grafit-off approved these changes
Good job 🔥

2022-08-30 07:20 UTC, grafit-off commented on src/styles/_catalog.scss
> +    transition: color 0.3s, transform 0.3s;
You can use variables for transition-duration.

2022-08-30 07:20 UTC, grafit-off commented on src/styles/_catalog.scss
> +      color: #34568b;
You can use variables for colors.

2022-08-30 07:20 UTC, grafit-off commented on src/styles/_header.scss
> +      color: #00acdc;
You can use variables for colors.

2022-08-30 07:20 UTC, grafit-off commented on src/styles/_header.scss
> +    transition: color 0.3s;
You can use variables for transition-duration.

2022-09-01 10:14 UTC, Denchepornyuk requested changes

2022-09-01 10:14 UTC, Denchepornyuk commented on src/index.html
> +      <a class="header__logo" href="/">
use `#` instead of `/` for href attribute, fix in all places

2022-09-01 10:14 UTC, Denchepornyuk commented on src/styles/_catalog.scss
>      border: 1px solid #ccc;
agree, create variables for colors

2022-09-05 11:47 UTC, Anna-Tkachenko approved these changes

2023-10-31 12:07 UTC, closed without merging