added styles
mate-academy/layout_catalog_hovers pull request #90
Opened 2021-09-18 13:37 UTC by d-hubych

- [DEMO LINK](https://d-hubych.github.io/layout_catalog_hovers/)

2021-09-18 14:37 UTC, DionStrzh requested changes
1. Виправити `transition`
2. Для `scale()` можеш записувати значення без одиниць вимірювань (1.2)

2021-09-18 14:37 UTC, DionStrzh commented on src/styles/_header.scss
> +      cursor: pointer;
1. Колір винеси в змінну
2. `cursor: pointer;` на `:hover` не став. По-перше, якщо хочеш, щоб на елементі змінювався курсор - давай це йому самому, а не через псевдоклас. По-друге, за замовчуванням лінкам встановлений `cursor: pointer;`

2021-09-18 14:37 UTC, DionStrzh commented on src/styles/_header.scss
> +    transition: 300ms;
1. Час можна винести в змінну
2. Явно вказуй для яких правил задаєш перехід

2021-09-18 14:40 UTC, DionStrzh commented on src/styles/_catalog.scss
> +    }
Для карточки разом з масштабуванням повинен змінюватись колір тексту.

2021-09-20 16:19 UTC, DionStrzh requested changes

2021-09-20 16:19 UTC, DionStrzh commented on src/styles/_variables.scss
> +$card-title-color: #34568b;
Відсутній пустий рядок

2021-09-20 16:19 UTC, DionStrzh commented on src/styles/_catalog.scss
> +    }
Забув додати для яких властивостей задаєш перехід

2021-09-20 20:16 UTC, DionStrzh requested changes

2021-09-20 20:16 UTC, DionStrzh commented on src/styles/main.scss
> +}
Давай розбиратись разом. 

`cursor: pointer;` ми задаємо елементам, які по задумці мають бути інтерактивними. Тобто інтерфейс буде інтуїтивно-зрозумілим користувачу, і при зміні курсору - він захоче щось з елементом зробити.

От наприклад, лінки (`<a href='#'></a>`) - який з них сенс? Правильно, посилання на той чи інший ресурс, або навігація на поточній сторінці. Тобто, якщо при наведенні на посилання залишається звичайний курсор - користувач не зрозуміє, що ця частина документу інтерактивна.

Тому для лінків і задаються його дефолтні стилі, такі як: колір(синій), підкреслювання та зміна курсору.

В даному випадку це правило потрібно опустити.

2021-09-20 20:16 UTC, DionStrzh commented on src/styles/_catalog.scss
> +    }
Поступово ти вже розумієш, що я хочу побачити в цьому завданні. 

Дивись, `transition`-правила можна розбити на наступні частини:

1. `transition-property:` - тут ми задаємо для яких правил ми застосовуємо наш перехід (в твоєму випадку все правильно, тобто - для `transform` та `color`)
2. `transition-duration:` - час за який виконається перехід (в твоєму випадку це час, який записаний в $transition-time)
3. `transition-timing-function:` - тут розраховуються проміжні значення для властивостей в стані переходу (в твоєму випадку не вказано, не обов'язково)
4. `transition-delay` - затримка перед виконанням переходу 

Але щоразу писати так буде незручно, код стане більше, перевіряти - явно не легше, тому використовується короткий запис `transition` який приймає наступні дані:

`transition: transition-property(1), transition-duration(2), transition-timing-function(3), transition-delay`

Більше того, ти можеш в одному правилі поєднувати для яких властивостей здійснюється перехід.
Наприклад, `transition: transform 3s, background-color 3s;`. Як бачиш, дані які ми не використовуємо - їх писати не обов'язково.

 Ось, що я від тебе чекаю: 
```suggestion
    transition: *CSS-правило* *час*, *CSS-правило* *час*;

    &:hover {
      transform: scale(1.2);
      color: $card-title-color;
    }
```

2021-09-21 08:34 UTC, d-hubych commented on src/styles/main.scss
> +}
> Давай розбиратись разом.
> 
> `cursor: pointer;` ми задаємо елементам, які по задумці мають бути інтерактивними. Тобто інтерфейс буде інтуїтивно-зрозумілим користувачу, і при зміні курсору - він захоче щось з елементом зробити.
> 
> От наприклад, лінки (`<a href='#'></a>`) - який з них сенс? Правильно, посилання на той чи інший ресурс, або навігація на поточній сторінці. Тобто, якщо при наведенні на посилання залишається звичайний курсор - користувач не зрозуміє, що ця частина документу інтерактивна.
> 
> Тому для лінків і задаються його дефолтні стилі, такі як: колір(синій), підкреслювання та зміна курсору.
> 
> В даному випадку це правило потрібно опустити.

Для цього я і задаю усім посиланням за замовчуванням cursor: pointer;
Ти пропонуєш його не задавати чи що?

2021-09-21 08:42 UTC, d-hubych commented on src/styles/_catalog.scss
> +    }
Погоджуюсь, `transition` можна записати одним рядком, але і не одним не є помилкою.
На даному етапі, для мене є зрозумілішим роздільний запис.

2021-09-21 09:18 UTC, DionStrzh commented on src/styles/main.scss
> +}
Так, тому що `cursor: pointer;` для посилань - налаштований за замовчуванням. Це означає, що тобі не потрібно явно задавати це правило. 
Тобто ось з описання - `cursor: pointer;` вказує на посилання. 
А посилання наші - a-тег - посилання) Тому для них вже цей курсор налаштований
![image](https://user-images.githubusercontent.com/57752461/134145153-80837b2b-d634-47c4-91f9-d3db390ece77.png)

2021-09-21 09:22 UTC, DionStrzh commented on src/styles/_catalog.scss
> +    }
> Погоджуюсь, `transition` можна записати одним рядком, але і не одним не є помилкою.
> На даному етапі, для мене є зрозумілішим роздільний запис.

Без питань, але в такому випадку виправ запис в `transition`.  Зараз у тебе там стоїть час виконання, якщо ти хочеш писати роздільно, то задай час в `transition-duration` правилі

2021-09-21 09:25 UTC, DionStrzh approved these changes
Мусолили-мусолили, уже набагато краще - розумієш коментарі. 
Прибери тільки `cursor: pointer;` для `тегу a`

2021-09-21 09:28 UTC, VinnieJ-2k20 approved these changes
Good job 👍 
Pay attention to default style values.

2021-09-21 09:28 UTC, VinnieJ-2k20 commented on src/styles/main.scss
> +}
Agree, this rule here is useless.

2023-01-14 15:13 UTC, closed without merging