Develop
mate-academy/layout_catalog_hovers pull request #969
Opened 2022-09-05 21:20 UTC by volodymyr4501

- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-09-06 19:24 UTC, Virass requested changes
And fix this glitch

https://www.loom.com/share/ba210e10ccb84763b14af4c8cec41ce7

2022-09-06 19:24 UTC, Virass commented on src/styles/_catalog.scss
> +    transition-duration: 300ms;
Use variable for duration

2022-09-06 19:24 UTC, Virass commented on src/styles/_header.scss
> +    transition-duration: 300ms;
Dublicate animation duration, use variable

2022-09-06 19:24 UTC, Virass commented on dist/index.html
> +<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Product</title><link rel="preconnect" href="https://fonts.googl
Why html minimized? Pls formating

2022-09-11 07:25 UTC, volodymyr4501 commented on dist/index.html
> +<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Product</title><link rel="preconnect" href="https://fonts.googl
![image](https://user-images.githubusercontent.com/110305930/189516785-471c70af-7c6d-43d7-a182-0daf9a0a8b99.png)
вроді б не згорнутий

2022-09-11 07:28 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-09-12 15:14 UTC, valerii-derkach requested changes

2022-09-12 15:14 UTC, valerii-derkach commented on src/styles/_catalog.scss
> +    }
use scale property instead of hardcoding width and height

2022-09-24 12:03 UTC, volodymyr4501 commented on src/styles/_catalog.scss
> +    }
я не знаю як це робити

2022-09-24 12:12 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-09-26 17:33 UTC, ArturErmolenko requested changes

2022-09-26 17:33 UTC, ArturErmolenko commented on src/styles/untils/blocks/_catalog.scss
> +    }
```suggestion    
    transition: transform $transition-duration, color $transition-duration;
     
      &:hover {
      transform: scale(1.2);
      color: #34568b;
    }
```

2022-09-26 17:33 UTC, ArturErmolenko commented on src/styles/_catalog.scss
> +    }
https://mate.academy/learn/css-advanced/transformations-and-animations#/video/937

2022-10-01 20:54 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-10-01 21:01 UTC, volodymyr4501 commented
maybe on this time demo link will be ok, I a bit fixed it.

2022-10-04 20:01 UTC, Bohdan-Maksymiuk requested changes
https://user-images.githubusercontent.com/94289038/193913146-258fb458-7ad3-43e2-a720-7a84d08b54e1.mov

this UI is buggy
code looks ok except one comment - You should specify transition properties directly
Default is all, but it could affect old browsers' performance 

ask in fe_chat and tag mentors - now looks like you code doesn't match the demo

2022-10-13 17:05 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-10-18 17:29 UTC, qoa11a requested changes
I see the same problems that were mentioned in previous comments.
Make sure you've deployed your changes. Otherwise, please, fix these mistakes, redeploy site and request review again.

2022-10-19 17:32 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)
-

2022-10-20 17:11 UTC, qoa11a requested changes
![image](https://user-images.githubusercontent.com/102293862/197014402-8e9d04ee-218a-4d87-9747-9cb55975f5fa.png)
If you have errors that you can see, please ask for help in the fe_chat in Slack instead of asking it in Pull Request.

2022-10-22 14:46 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-10-22 14:46 UTC, volodymyr4501 commented
Виправив марджин думаю тепер ок

2022-10-22 14:46 UTC, volodymyr4501 commented
> Виправив марджин, думаю тепер ок.

2022-10-24 07:07 UTC, stanislav-topikha requested changes

2022-10-24 07:07 UTC, stanislav-topikha commented on src/styles/untils/blocks/_catalog.scss
> +  max-width: 744px;
why? there should be 4 cards in a row

2022-10-25 16:22 UTC, volodymyr4501 commented
I don't understand why you see 944 pixels if I made 744 pixels and I did npm deploy

2022-10-25 16:22 UTC, volodymyr4501 commented
![image](https://user-images.githubusercontent.com/110305930/197829271-afec5e01-ea63-4e53-b8a3-2dc369be5d21.png)

2022-10-25 16:23 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-10-25 18:43 UTC, volodymyr4501 commented
- [DEMO LINK](https://volodymyr4501.github.io/layout_catalog_hovers/)

2022-10-26 09:01 UTC, polosanya requested changes
Cards are not centered. Also, there should be 4 cards in a row.
Seems like you somehow changed default styles. You should only add hovers 
![image](https://user-images.githubusercontent.com/96409563/197982139-381ff7c8-d1ad-4f5f-b6fa-c928ce07716f.png)

2022-10-26 14:53 UTC, closed without merging